services:
  filmlibrarymanagement:
    image: filmlibrarymanagement
    build:
      context: .
      dockerfile: Dockerfile
    container_name: filmlibrary_app
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=true
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_db
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "StrongP@ssw0rd!"
      ACCEPT_EULA: "Y"
