# Docs for Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

# name: Build, Test, and Deploy ASP.NET Core API Container to Azure Web App

# on:
#   push:
#     branches:
#       - master
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       Checkout source code
#       - uses: actions/checkout@v4

#       Set up .NET SDK
#       - name: Setup .NET SDK
#         uses: actions/setup-dotnet@v4
#         with:
#           dotnet-version: '8.0.x'

#       Restore dependencies
#       - name: Restore dependencies
#         run: dotnet restore ./FilmLibraryManagement.sln

#       Build the project
#       - name: Build the project
#         run: dotnet build ./FilmLibraryManagement.sln --configuration Release --no-restore

#       Run tests
#       - name: Run tests
#         run: dotnet test ./FilmLibraryManagement.sln --configuration Release --no-restore --verbosity normal

#       Set up Docker Buildx
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2

#       Log in to Docker Hub
#       - name: Log in to container registry
#         uses: docker/login-action@v2
#         with:
#           registry: https://index.docker.io/v1/
#           username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_7D545A14DE8B4F8785716175FE77F3F6 }}
#           password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_CCBD151DEDE045D7B133441595A62C6D }}


#       Build and push container image to Docker Hub
#       - name: Build and push container image to registry
#         uses: docker/build-push-action@v3
#         with:
#            context: ./FilmLibraryManagement  Pointing to the correct directory
#            push: true
#            tags: index.docker.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_7D545A14DE8B4F8785716175FE77F3F6 }}/zwen2002/filmlibrarymanagement:${{ github.sha }}
#            file: ./FilmLibraryManagement/Dockerfile  Path to Dockerfile





#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     environment:
#       name: 'Production'
#       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

#     steps:
#       Deploy to Azure Web App using Docker image
#       - name: Deploy to Azure Web App
#         id: deploy-to-webapp
#         uses: azure/webapps-deploy@v2
#         with:
#           app-name: 'film-library-api'
#           slot-name: 'Production'
#           publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D7B0096658224925810698635A44C7B1 }}
#           images: 'index.docker.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_7D545A14DE8B4F8785716175FE77F3F6 }}/zwen2002/filmlibrarymanagement:${{ github.sha }}'
