name: Build and Deploy ASP.NET Core API with Docker

on:
  push:
    branches:
      - master  # Trigger on push to the master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Setup .NET SDK
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    # Step 3: Restore dependencies
    - name: Restore dependencies
      run: dotnet restore ./FilmLibraryManagement.sln

    # Step 4: Build the project
    - name: Build the project
      run: dotnet build ./FilmLibraryManagement.sln --configuration Release --no-restore

    # Step 5: Run tests
    - name: Run tests
      run: dotnet test ./FilmLibraryManagement.sln --configuration Release --no-restore --verbosity normal

    # Step 6: Publish the app
    - name: Publish the app
      run: dotnet publish ./FilmLibraryManagement/FilmLibraryManagement.csproj --configuration Release --no-restore --no-build -o ./publish

    # Step 7: Install Docker Compose (if needed)
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    # Step 8: Navigate to the directory with docker-compose.yml and build Docker image
    - name: Build Docker image
      run: |
        cd FilmLibraryManagement  # Navigate to the subfolder where docker-compose.yml is located
        docker-compose -f docker-compose.yml build filmlibrarymanagement
      env:
        DOCKER_BUILDKIT: 1
