# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - film-library-api

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_7173c95ba9384c61a0ca57d71fe20da0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f02b4f091701459d9cff0a026d1d55aa }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_7173c95ba9384c61a0ca57d71fe20da0 }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'film-library-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_32621366ece44d40b5200f41988cbcd2 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_7173c95ba9384c61a0ca57d71fe20da0 }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}'